command:
- ${interpreter}
- ${program}
- --do_predict
- ${args}
method: bayes
metric:
  goal: maximize
  name: best_dev_avg_weak_hits@1
name: MetaQA-3hop-eval
parameters:
  add_dist_feature:
    value: 1
  add_inv_edges_to_edge_index:
    values:
      - 1
  data_dir:
    value: /mnt/nfs/work1/mccallum/rajarshi/cbr-weak-supervision/MetaQA-synthetic/3-hop/
  dataset_name:
    value: metaqa
  eval_batch_size:
    value: 1
  eval_steps:
    value: 1024
  gradient_accumulation_steps:
    values:
    - 2
    - 8
  learning_rate:
    distribution: uniform
    max: 0.001
    min: 0.0001
  logging_steps:
    value: 10
  loss_metric:
    value: txent
  max_grad_norm:
    value: 1
  num_gcn_layers:
    value: 3
  num_neighbors_eval:
    values:
      - 5
      - 7
      - 10
  num_neighbors_train:
    values:
      - 5
      - 7
      - 10
  num_train_epochs:
    value: 5
  output_dir:
    value: /mnt/nfs/scratch1/rajarshi/cbr-weak-supervision/expts/metaqa_3hop/
  save_steps:
    value: 80
  save_total_limit:
    value: 1
  task:
    value: pt_match
  train_batch_size:
    value: 1
  temperature:
    distribution: uniform
    max: 0.1
    min: 0.001
  transform_input:
    value: 1
  use_fast_rgcn:
    value: 1
  use_wandb:
    value: 1
program: runner.py
project: cbr-weak-supervision